CREATE DATABASE zhiye DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci;

CREATE TABLE IF NOT EXISTS `user` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(128),
  username VARCHAR (128) NOT NULL,
  password VARCHAR (128) NOT NULL,
  phone VARCHAR(128),
  email VARCHAR(128),
  klass INT(11),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `company` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(128),
  username VARCHAR (128) NOT NULL,
  password VARCHAR (128) NOT NULL,
  phone VARCHAR(128),
  email VARCHAR(128),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `stu_info_1` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(128),
  highestDegree VARCHAR (128) NOT NULL,
  workYears VARCHAR (128) NOT NULL,
  phone VARCHAR(128),
  email VARCHAR(128),
  city VARCHAR(128),
  uId INT(11),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `stu_info_1` ADD FOREIGN KEY (`uId`) REFERENCES `user` (`id`);

CREATE TABLE IF NOT EXISTS `stu_info_2` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  school VARCHAR(128),
  major VARCHAR (128) NOT NULL,
  degree VARCHAR (128) NOT NULL,
  graduate VARCHAR(128),
  uId INT(11),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `stu_info_2` ADD FOREIGN KEY (`uId`) REFERENCES `user` (`id`);

CREATE TABLE IF NOT EXISTS `stu_info_3` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  company VARCHAR(128),
  job VARCHAR (128) NOT NULL,
  startTime VARCHAR (128) NOT NULL,
  endTime VARCHAR(128),
  uId INT(11),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `stu_info_3` ADD FOREIGN KEY (`uId`) REFERENCES `user` (`id`);

CREATE TABLE IF NOT EXISTS `stu_info_4` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  word TEXT,
  uId INT(11),
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `stu_info_4` ADD FOREIGN KEY (`uId`) REFERENCES `user` (`id`);